import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import Header from '@/components/layout/header';
import ReduxProvider from '@/providers/react-redux';
import ReactQueryProvider from '@/providers/react-query';

const dm_sans = localFont({
  src: [
    {
      path: '../../public/fonts/DM_Sans/DMSans-VariableFont_opsz,wght.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/DM_Sans/DMSans-VariableFont_opsz,wght.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/DM_Sans/DMSans-VariableFont_opsz,wght.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/DM_Sans/DMSans-Italic-VariableFont_opsz,wght.ttf',
      weight: '600',
      style: 'italic',
    },
    {
      path: '../../public/fonts/DM_Sans/DMSans-VariableFont_opsz,wght.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-dm-sans',
});

const bricolage_grotesque = localFont({
  src: [
    {
      path: '../../public/fonts/Bricolage_Grotesque/BricolageGrotesque-VariableFont_opsz,wdth,wght.ttf',
      weight: '700',
    },
  ],
  variable: '--font-bricolage-grotesque',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dm_sans.variable} ${bricolage_grotesque.variable} antialiased`}
      >
        <ReduxProvider>
          <ReactQueryProvider>
            <div className="max-w-desktop mx-auto px-8">
              <Header />
              {children}
            </div>
          </ReactQueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
